name: ithemal # Or whatever name you prefer
channels:
  - defaults  # Prioritize defaults where many Py2.7 core libs likely reside
  - conda-forge
  - pytorch   # If attempting to install PyTorch
  - free      # For mysql-connector-python=2.0.4 from your list
channel_priority: strict
dependencies:
  - defaults::python=2.7.16  # Pin specific patch version if possible
  - defaults::pip=19.2.3
  - defaults::numpy=1.15.4
  - defaults::scipy=1.1.0
  - defaults::pandas=0.23.4
  - defaults::six=1.12.0
  - free::mysql-connector-python=2.0.4 # Note 'free' channel
  # - scikit-learn
  # - matplotlib
  # - pyqt
